apiVersion: v1

kind: Service

metadata:

  labels:

    app: services-db

  name: services-db

spec:

  selector:

    app: bookstack-back 

    tier: backend

  type: ClusterIP

  ports:
    
    - protocol: TCP

      port: 3306

      targetPort: 3306

