apiVersion: v1

kind: Service

metadata:

  name: bookstack-service-web

spec:

  type: NodePort

  selector:

    app: bookstack-front

    tier: frontend

  ports:

    - targetPort: 8080

      port: 8080

      nodePort: 30009
